### ISSUE TITLE
put the files in organized manner

### ISSUE THREAD

**Issue by himanshujaidka** [himanshujaidka/dailymint#13]

**Comment by sarthak55k** [comment]
can you please elaborate which files?

**Comment by sarthak55k** [comment]
can i do it?

**Comment by N0ahMC** [comment]
explain

**Comment by himanshujaidka** [comment]
all the .html files in one folder and readme, code of conduct in another folder

**Comment by sarthak55k** [comment]
can i do it? please!

**Comment by himanshujaidka** [comment]
@N0ahMC69 pls have a look at other issues :)

**Comment by N0ahMC** [comment]
yeah... but I'll do it better

**Comment by himanshujaidka** [comment]
@sarthak55k go ahead

**Comment by N0ahMC** [comment]
:(

**Comment by himanshujaidka** [comment]
@N0ahMC69 have a look at #14 issue and if @sarthak55k will not able to do then it will assigned to you

**Comment by sarthak55k** [comment]
Thanks
I will do it

**Comment by sarthak55k** [comment]
i have to keep the index.html and style.css in the main folder itself right?
and where should i put the contribution.md and news.ico??

**Comment by sarthak55k** [comment]
i have to keep the index.html and style.css in the main folder itself right?
and where should i put the contributing.md and news.ico??

**Comment by himanshujaidka** [comment]
> i have to keep the index.html and style.css in the main folder itself right?
> and where should i put the contributing.md and news.ico??

make ass and put all css files inside that and keep index.html as it is and add all HTML files in one folder other than index.html

**Comment by sarthak55k** [comment]
is it ok as  you have merged recently??

**Comment by himanshujaidka** [comment]
yeah, I'll manage it
