### ISSUE TITLE
add contributors to readme

### ISSUE THREAD

**Issue by himanshujaidka** [himanshujaidka/dailymint#14]

**Comment by N0ahMC** [comment]
seems easy enough

**Comment by himanshujaidka** [comment]
@N0ahMC69 interested?

**Comment by N0ahMC** [comment]
sure

**Comment by N0ahMC** [comment]
done

**Comment by himanshujaidka** [comment]
remove my pic  and add contributor's pic instead of it

**Comment by N0ahMC** [comment]
@himanshujaidka what do you mean?

**Comment by himanshujaidka** [comment]
remove my pic from the contributor's section because my pic is already there, instead of my profile add the contributor, got that?
