### ISSUE TITLE
Add login feature

### ISSUE THREAD

**Issue by himanshujaidka** [himanshujaidka/dailymint#2]
We could add a login feature and user get a notification after news update

**Comment by devblin** [comment]
Hey, I would like to work on this issue, can you please give more details ?

**Comment by himanshujaidka** [comment]
yes, if there should be a login feature in this so that user gets an update after daily updation of news and for that, we have to add a backend system

**Comment by himanshujaidka** [comment]
any updates @devblin

**Comment by JainDivyansh16** [comment]
I would love to work on this issue. Provide some more information about this.

**Comment by himanshujaidka** [comment]
Let’s give Slack a try -- it’s a simple, focused messaging app for teams that work together. Sign up here:
https://join.slack.com/t/dailymintworkspace/shared_invite/zt-i03wzbf8-hZchYvId2mWocJ82TW8SQQ
@1661Divyansh join this slack channel
