### ISSUE TITLE
Feature request: Add html page instead of google forms

### ISSUE THREAD

**Issue by himanshujaidka** [himanshujaidka/dailymint#3]

**Comment by himanshujaidka** [comment]
Replace all google forms with html or own created web page

**Comment by azim2429** [comment]
Hey @himanshujaidka I would like to work on this issue.

**Comment by himanshujaidka** [comment]
ok go on :)

**Comment by himanshujaidka** [comment]
but first show me UI before implementing it

**Comment by azim2429** [comment]
Yeah sure!

**Comment by azim2429** [comment]
> but first show me UI before implementing it

Should I mail you or send a code pen link here itself for the UI.

**Comment by himanshujaidka** [comment]
Attach output here or send it to me on slack as I am on slack : Himanshu Jaidka

**Comment by azim2429** [comment]
> Attach output here or send it to me on slack as I am on slack : Himanshu Jaidka

https://codepen.io/_azzim_/full/BaKbLwM

**Comment by himanshujaidka** [comment]
this form is for what?

**Comment by azim2429** [comment]
> this form is for what?

This is just for verifying the UI. If the UI is okay then I will be replacing this form with the **submit a news** form.

**Comment by himanshujaidka** [comment]
okay replace that

**Comment by himanshujaidka** [comment]
any updates @azim2429

**Comment by azim2429** [comment]
> any updates @azim2429

yes I am almost done. Only few minor changes are remaining.

**Comment by azim2429** [comment]
![daily_news](https://user-images.githubusercontent.com/60839140/94771391-b46e2700-03d4-11eb-83b3-82e4feffa301.png)
Please check and feel free to give suggestions or do any changes

**Comment by himanshujaidka** [comment]
great work! @azim2429

**Comment by azim2429** [comment]
I'm glad you liked it. Should I create pull request?

**Comment by himanshujaidka** [comment]
yes, sure

**Comment by azim2429** [comment]
hey @himanshujaidka contact form and feedback are yet to be replaced.

**Comment by himanshujaidka** [comment]
I think

**Comment by himanshujaidka** [comment]
for more details, stay tuned to issue no #6
