### ISSUE TITLE
Require Documentation

### ISSUE THREAD

**Issue by himanshujaidka** [himanshujaidka/dailymint#5]

**Comment by hritik5102** [comment]
Hello @himanshujaidka, I would like to work on this issue.

**Documentation includes**

- [x]  gitignore
- [x]  code of conduct.md
- [x]  Contribution.md
- [x]  Neccasary changes in ReadMe ( adding badges and gitpod)
- [x]  MIT Licence

Thank you

**Comment by himanshujaidka** [comment]
and add little bit description about it and also about contributors

**Comment by himanshujaidka** [comment]
any updates ? @hritik5102

**Comment by hritik5102** [comment]
Sorry, I was busy though, I'll complete the documentation in a while

**Comment by aastha-b** [comment]
Can I do this?

**Comment by hritik5102** [comment]
@himanshujaidka Check out PR #10, I have added the documentation

Thank you :)

**Comment by himanshujaidka** [comment]
Thanks for your patch
