### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by himanshujaidka** [himanshujaidka/dailymint#6]

**Comment by petulla28** [comment]
Hey! Can u please brief me about this issue

**Comment by petulla28** [comment]
I am new to open source, and I am interested to solve this.

**Comment by himanshujaidka** [comment]
need UI for contact and feedback me at the end of every page, in which we will have two fields, one is for contact and one is for feedback(rating system)

**Comment by azim2429** [comment]
Hey @himanshujaidka  I am working on the UI for contact and feedback form.
![image](https://user-images.githubusercontent.com/60839140/94846154-4c542b00-043e-11eb-9965-df3ad3112a07.png)
This is a preview , if you feel to do any changes , please ping me

**Comment by petulla28** [comment]
ok can I work on this?

**Comment by himanshujaidka** [comment]
@azim2429 ok till the time we will keep that, make a pr

**Comment by himanshujaidka** [comment]
> ok can I work on this?



> ok can I work on this?

make a UI for e-paper feature, in which our app provides a daily e-paper of 4-5 organizations, add their logo and make a blueprint first or otherwise, I'll provide if you are not able to design well

**Comment by petulla28** [comment]
@himanshujaidka is there any other work for UI?

**Comment by petulla28** [comment]
@himanshujaidka Ok I will work on e-paper UI

**Comment by himanshujaidka** [comment]
> @himanshujaidka is there any other work for UI?

till the time do this or if you notice anything and if you feel that anything to be changed then raise the issue

**Comment by petulla28** [comment]
sure

**Comment by petulla28** [comment]
@himanshujaidka Plz check the UI for e-paper template on the link below 
https://www.figma.com/file/t0GpMZ9nRc4TyfdG6SgB4c/OPEN-SOURCE-UI?node-id=0%3A1

**Comment by azim2429** [comment]
![image](https://user-images.githubusercontent.com/60839140/94906190-ab0bba00-04bb-11eb-8779-f0b1d0927b41.png)

Is the UI and input fields okay for the feedback form?

**Comment by himanshujaidka** [comment]
@azim yes, make a pr

**Comment by himanshujaidka** [comment]
> @himanshujaidka Plz check the UI for e-paper template on the link below
> https://www.figma.com/file/t0GpMZ9nRc4TyfdG6SgB4c/OPEN-SOURCE-UI?node-id=0%3A1

yes, make a pr

**Comment by Azim** [comment]
> @Azim yes, make a pr

excuse me?

**Comment by azim2429** [comment]
Yes , I am creating, sorry for the delay

**Comment by petulla28** [comment]
@himanshujaidka Yes, making

**Comment by petulla28** [comment]
Hey ! actually I am new to open source so can you please help me. As I have
only made a UI of e-paper page and no the html , so shall I upload only css
file ?

**Comment by petulla28** [comment]
Do we have html for e-paper feature, because without html css won't work.
So can you please help me?

**Comment by petulla28** [comment]
@himanshujaidka Creating html for e-paper, then will create pr

**Comment by petulla28** [comment]
Like of we don't have html code for the particular page , I will make it n
upload it. Just need some time for that.

**Comment by himanshujaidka** [comment]
@petulla28 no worries, take your time

**Comment by petulla28** [comment]
Ok thanks

**Comment by himanshujaidka** [comment]
Let’s give Slack a try -- it’s a simple, focused messaging app for teams that work together. Sign up here:
https://join.slack.com/t/dailymintworkspace/shared_invite/zt-i03wzbf8-hZchYvId2mWocJ82TW8SQQ
join this slack channel

**Comment by petulla28** [comment]
Hey! I have made all html and css for e-paper page, can you please help me how to create PR directly from github. I am new to open source so I am facing some issues.

**Comment by petulla28** [comment]
@himanshujaidka Hey! I have created PR for e-paper page, please look into this.
