### ISSUE TITLE
Captcha required 

### ISSUE THREAD

**Issue by himanshujaidka** [himanshujaidka/dailymint#9]
Captcha on submitting a news form

**Comment by azim2429** [comment]
Do you need only a I'm not a Robot check or a some verification like matching photos?

**Comment by nindroz** [comment]
can I take this?

**Comment by himanshujaidka** [comment]
@azim2429 I am workin on it and at the start, we require a simple captcha box and later on we will work on the robot captcha

**Comment by himanshujaidka** [comment]
@nindroz please have a look at other issues, thank you :)
